config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'contact' => 'home#contact'
  get 'moisture' => 'home#moisture'
  get 'experience' => 'home#experience'
  get 'about_us' => 'home#about_us'
  get 'faq' => 'home#faq'
  get 'tr5' => 'home#tr5'
  get 'tr20' => 'home#tr20'
  get 'tr50' => 'home#tr50'
  get 'mms90' => 'home#mms90'
  get 'solutions' => 'home#solutions'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def moisture
  end

  def experience
  end

  def contact
  end

  def faq
  end

  def mms90
  end

  def tr5
  end

  def tr20
  end

  def tr50
  end

  def solutions
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/views/home/about_us.html.erb
<div class="">
  <div class="about-first-section">
    <div style="height: inherit; background-color: rgba(255,255,255,0.7);display: flex; justify-content: center; align-items: center">
      <h1 class="grey-font" style="font-size: 96px">ABOUT US</h1>
    </div>
  </div>

  <div class="about-quote-section">
    <div class="quote-inner">
      <div class="container" style="padding: 10px 50px 30px">
        <div class="text-center">
          <img class="img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5abba80bbd3b5uNN896P/Screen-Shot-2018-03-28-at-17.33.12-copy.png">
          <p class="white-font">I imagine a world where everyone feels safe at work.
            It has been my driving motivation for over 25 years to create a safe and efficient workplace.
            This philosophy is at the heart of every decision I make and every path I take.
            It is for this reason that I chose to remain focused within the reliability and condition-based
            maintenance field and
            the technologies that AVACO brings to the market allows us to fulfill our obligations and
            responsibilities to our clients.
          </p>
          <p class="white-font">
            Our clients have an immense responsibility to provide clean,
            reliable and sustainable power to their users and we can help with this.
          </p>
          <p class="white-font">- Ajay Chikermane,  Founder Director</p>
        </div>
      </div>

    </div>
  </div>

  <div class="who-we-are-section">
    <div class="container" style="padding: 30px 50px">
      <h3 class="about-heading dark-blue">WHO WE ARE & WHAT WE DO</h3>
      <div style="display: flex; justify-content: space-around; flex-wrap: wrap; margin-top: 15px;">
        <div style="flex: 1">
          <p>
            AVACO has been at the forefront in the world of Reliability for over two
            decades now and we are not showing any signs of slowing down.
          </p>
          <p>
            Mr. Arun Chikermane’s vision of AVACO has taken the company through 20 successful years of operation.
            His un-nerving dedication and focused hard work has enabled AVACO to be known as one of the leading
            providers of globally
            recognized products and solutions within the field of Reliability and Condition Based Maintenance.
          </p>
          <p>
            Over the years AVACO has been expanding in the Middle East and has earned a
            reputation for providing quality
            Equipment Reliability Solutions to various Utilities and Large Industries.
          </p>
        </div>
        <div style="width: 100px; height: inherit;display: flex;
          justify-content: center;
          padding-top: 15px
          ">
          <div style="border-left: 1px solid black; height: 90%"></div>
        </div>
        <div style="flex: 1">
          <p>
            The AVACO group of companies was established in 1994 and has evolved into a leader in the field of
            Predictive Maintenance and Condition Monitoring over the last 23 years.
          </p>
          <p>
            DryTrans is a brand of moisture management systems under the AVACO banner.
            It is a result of two decades of industry experience. AVACO Solutions is based out of SHARJAH,
            U.A.E. DryTrans is designed and manufactured in the United Arab Emirates.
          </p>
          <p>
            DryTrans has been developed completely in-house, under the AVACO banner and is currently being manufactured in the Sharjah Airport Free Zone.
            Support for DryTrans is offered through AVACO International as well as AVACO Solutions FZC.
          </p>
        </div>
      </div>

      <div>
        <h3 class="about-heading dark-blue">OUR CORE</h3>
        <div style="display: flex; flex-wrap: wrap;">
          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90ba5d465bpmWby8X/download-copy_d200.png" style="margin-top: 0px; margin-left: 0px;"> -->
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90ba5d465bpmWby8X/download-copy_d200.png" width="83" height="83" style="width: 83px; height: 83px; margin-top: 23px; margin-left: 0px;">
            </div>
            <div class="icon-heading">We work in highly regulated environments managing complex assets.</div>
          </div>

          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c64daab9fZymewoe/15214-200.png" style="margin-top: 0px; margin-left: 0px;"> -->
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c64daab9fZymewoe/15214-200.png" width="87" height="87" style="width: 87px; height: 87px; margin-top: 25px; margin-left: 0px;">
            </div>
            <div class="icon-heading">We maintain and manage expensive essential equipment for a range of government bodies and private sector customers.</div>
          </div>

          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c64e2cb25GMYPvRN/142733-200.png" style="margin-top: 0px; margin-left: 0px;"> -->
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c64e2cb25GMYPvRN/142733-200.png" width="86" height="86" style="width: 86px; height: 86px; margin-top: 20px; margin-left: 0px;">
            </div>
            <div class="icon-heading">We provide our clients with better capability, reliability and availability of their critical assets, and in doing so provide significant cost savings.</div>
          </div>
        </div>
        <div style="display: flex; flex-wrap: wrap;">
          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c7af4fd29oM8OLzd/546234-200.png" style="margin-top: 0px; margin-left: 0px;"> -->
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab8c7af4fd29oM8OLzd/546234-200.png" width="70" height="70" style="width: 70px; height: 70px; margin-top: 37px; margin-left: 0px;">
            </div>
            <div class="icon-heading">We provide in-depth and detailed site and classroom training on our varied product ranges. </div>
          </div>

          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90bafacb74tK0jh87/consult_icon_d200.png" width="104" height="78" style="width: 104px; height: 78px; margin-top: 35px; margin-left: 0px;">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90bafacb74tK0jh87/consult_icon_d200.png" style="margin-top: 0px; margin-left: 0px;"> -->
            </div>
            <div class="icon-heading">We consult with the client on the site requirements and the materials required.</div>
          </div>

          <div class="small-icon-innercontainer">
            <div class="core-icon-container">
              <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90bb9a9c9dTDfgPER/1_d200.png" width="147" height="77" style="width: 147px; height: 77px; margin-top: 36px; margin-left: -35px;">
              <!-- <img class="small-icon img-responsive" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab90bb9a9c9dTDfgPER/1_d200.png"  style="margin-top: 0px; margin-left: -35px;"> -->
            </div>
            <div class="icon-heading">We have the in-house ability to offer installation and commissioning services for the products that we promote.</div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/home/contact.html.erb
<div class="">
  <div class="contact-us-first-section">
    <div class="contact-us-first-section-inner">
      <h1 class="grey-font" style="font-size: 96px">CONTACT US</h1>
    </div>
  </div>

  <div class="map-section">
    <div id="map" style="width:100%; height:400px;background:yellow"></div>
  </div>


  <div class="contact-parallax">
  <div class="grey-details-section">
    <div class="container" style="padding: 10px 50px">
      <div style="display: flex; flex-wrap: wrap; justify-content: center;">
        <div class="contact-details">
          <div>
            <i class="fa fa-map-marker" style="font-size: 25px; margin-bottom: 15px"></i>
            <div class=""><p class="footer-grey-heading">OFFICE ADDRESS</p></div>
            <address style="margin-bottom: 16px">
              <div class="" style="margin-bottom: 0px">
                Sharjah Airport Free Zone. SAIF
              </div>
              <div class="" style="margin-bottom: 0px">
                Zone. Q3 – 53 Sharjah,
              </div>
              <div class="" style="margin-bottom: 0px">
                United Arab Emirates
              </div>
            </address>
            <div>
              <p>Email:</p>
              <p><a href="mailto:support@drytrans.com">support@drytrans.com</a></p>
            </div>
            <div>
              <p>Telephone:</p>
              <p>+971 6-5272626</p>
            </div>
            <div>
              <p>Fax:</p>
              <p>+971 6-5738597 </p>
            </div>
          </div>

        </div>
        <div class="contact-details">
          <div>
            <i class="fa fa-cog" style="font-size: 25px; margin-bottom: 15px"></i>
            <div class=""><p class="footer-grey-heading">TECHNICAL DIRECTOR</p></div>
            <div style="margin-bottom: 26px">
              <p style="margin-top: 25px">Contact Person:</p>
              <p>Vishal Patil</p>
            </div>
            <div>
              <p>Email:</p>
              <p><a href="mailto:vishal@drytrans.com">vishal@drytrans.com</a></p>
            </div>
            <div>
              <p>Telephone:</p>
              <p>+97155-6790417</p>
            </div>
            <div>
              <p>Fax:</p>
              <p>+971 6-5738597</p>
            </div>
          </div>

        </div>

        <div class="contact-details">
          <div>
            <i class="fa fa-male" style="font-size: 25px; margin-bottom: 15px"></i>
            <div class=""><p class="footer-grey-heading">SALES</p></div>
            <div style="margin-bottom: 26px">
              <p style="margin-top: 25px">Contact Person:</p>
              <p>Ajay Chikermane</p>
            </div>
            <div>
              <p>Email:</p>
              <p><a href="mailto:ajay@drytrans.com">ajay@drytrans.com</a></p>
            </div>
            <div>
              <p>Telephone:</p>
              <p>+97150-5971357</p>
            </div>
            <div>
              <p>Fax:</p>
              <p>+971 6-5738597</p>
            </div>
          </div>

        </div>
        <div class="contact-details">
          <div>
            <i class="fa fa-user" style="font-size: 25px; margin-bottom: 15px"></i>
            <div class=""><p class="footer-grey-heading">ADMINISTRATION</p></div>
            <div style="margin-bottom: 26px">
              <p style="margin-top: 25px">Contact Person:</p>
              <p>Ashitha Shetty</p>
            </div>
            <div>
              <p>Email:</p>
              <p><a href="mailto:ashitha@drytrans.com">ashitha@drytrans.com</a></p>
            </div>
            <div>
              <p>Telephone:</p>
              <p>+97155-3228623</p>
            </div>
            <div>
              <p>Fax:</p>
              <p>+971 6-573 8597</p>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>

  <div class="contact-form-container">
    <div class="container" style="padding: 30px 50px;">

      <form action="" style="position: relative">
        <div class="form-warning" id="form-empty-warning" style="width: 500px;">
          <div style="display: flex; justify-content: flex-end; padding:15px 15px 0px">
            <i class="fa fa-close" id="warn-close" style="color: white; font-size: 25px; cursor: pointer"></i>
          </div>
          <div style="margin-top: -16px; width: 100%; height: 85%; z-index: -100; display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;">
            <p class="white-font text-center warning-text" id="first-warn-text"></p>
            <p class="white-font text-center warning-text" id="second-warn-text"></p>
          </div>
        </div>
        <div style="display: flex; flex-wrap: wrap;">
          <div style="flex: 1; padding: 20px">
            <div class="input-container">
              <label for="">Name</label>
              <input id="contact-name-field"type="text">
            </div>
            <div class="input-container">
              <label for="">Email</label>
              <input id="contact-email-field" type="email">
            </div>
            <div class="input-container">
              <label for="">Phone</label>
              <input type="text" id="contact-phone-field">
            </div>
          </div>
          <div style="flex: 1; padding: 20px">
            <div class="input-container">
              <label for="">Company Name</label>
              <input type="text" id="contact-company-field">
            </div>
            <div class="input-container">
              <label for="">Message</label>
              <textarea name="name" rows="5" cols="40" id="contact-message-field"></textarea>
            </div>
          </div>
        </div>
        <div style="display: flex; justify-content: flex-end; padding-right: 15px">
          <input class="submit-button" id="contact-form-submit" type="Submit">
        </div>
      </form>
    </div>
  </div>

  <div class="grey-details-section">
    <div class="container" style="padding: 10px 50px">

      <h2 style="width: 80%; margin: 50px auto" class="footer-grey-heading text-center">
        GLOBAL PRESENCE THROUGH OUR PARTNERS
      </h2>
      <div style="display: flex; flex-wrap: wrap; justify-content: center; align-items: center; margin-bottom: 40px">
        <div class="blue-icon-container">
          <i class="fa fa-map-marker blue-icon"></i>
          <span style="font-size: 20px">
            EMEA
          </span>
        </div>

        <div class="blue-icon-container">
          <i class="fa fa-map-marker blue-icon"></i>
          <span style="font-size: 20px">
            ASIA & PACIFIC
          </span>
        </div>

        <div class="blue-icon-container">
          <i class="fa fa-map-marker blue-icon"></i>
          <span style="font-size: 20px">
            NORTH AMERICA
          </span>
        </div>

        <div class="blue-icon-container">
          <i class="fa fa-map-marker blue-icon"></i>
          <span style="font-size: 20px">
            SOUTH AMERICA
          </span>
        </div>


      </div>
    </div>
  </div>
</div>
</div>

app/views/home/experience.html.erb
<div class="">
  <div class="experience-first-section">
    <div style="height: inherit; background-color: rgba(255,255,255,0.7);display: flex; justify-content: center; align-items: center">
      <h1 class="grey-font" style="font-size: 100px">EXPERIENCE</h1>
    </div>
  </div>

  <div class="experience-grey-section">
    <div class="experience-grey-section-inner">
      <div class="container" style="padding: 50px">
        <div class="text-center" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
          <ul style="padding: 0; margin: 0">
            <li style="display: flex; margin-bottom: 15px; align-items: center">
              <i class="fa fa-download" style="font-size: 23px; margin-right: 15px; color: black"></i>
              <a href="https://storage.googleapis.com/wzukusers/user-22488641/documents/5ac09bc969af4YkhAHLl/17-09-14-DT-Case%20Study-DUBAL-MMS90.pdf" class="experience-download-link">
                Pilot project installed at Dubal, Jebel Ali, Dubai United Arab Emirates - January 17, 2017
              </a>
            </li>
            <li style="display: flex; align-items: center">
              <i class="fa fa-download" style="font-size: 23px; margin-right: 15px; color: black"></i>
              <a href="https://storage.googleapis.com/wzukusers/user-22488641/documents/5ac09bc9ee5a4TbvoU6f/18-03-11-DEWA%20Gen%20Stn-TR5.pdf" class="experience-download-link">
                Pilot project installed at D.E.W.A, Dubai, United Arab Emirates - January 21, 2018
              </a>
            </li>
            <p class="experience-note">(Click to download and view the case studies)</p>
          </ul>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <div class="container" style="display: flex; justify-content: center; padding: 50px 0px; flex-wrap: wrap; align-items: cnetre">
      <div class="footer-inner-section">
        <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab78ce0cb0065hDQIeh/DT-LOGO_d400.png" width="215" height="136" style="width: 215px; height: 136px; margin-top: 0px; margin-left: 0px;">
        <p class="white-font">
          DryTrans is a brand of moisture management systems under the AVACO banner. It is a result of two decades of industry experience. AVACO Solutions is based out of SHARJAH, U.A.E. DryTrans is designed and manufactured in the United Arab Emirates
        </p>
      </div>
      <div class="footer-inner-section">
        <div class="footer-grey-heading">
          <span class="grey-font">QUICK LINKS</span>
        </div>
        <ul class="footer-nav" style="margin-bottom: 35px">
          <li class="blue-circle">
            <%= link_to 'HOME', root_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'ABOUT US', about_us_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'MOISTURE', moisture_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'SOLUTIONS', solutions_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'EXPERIENCE', experience_path, :class => 'white-font' %>
          </li>
        </ul>

        <div class="footer-grey-heading">
          <span class="grey-font">DOWNLOADS</span>
        </div>
        <ul class="footer-nav">
          <li class="blue-circle">
            <a  target="_blank" href="https://storage.googleapis.com/wzukusers/user-22488641/documents/5ac08127b2357u74o1WV/DT%20Brochure%20(UAE).pdf" class="white-font">PRODUCT CATALOGUE</a>
          </li>
        </ul>

      </div>
      <div class="footer-inner-section">
        <div class="footer-grey-heading">
          <span class="grey-font">SUPPORT</span>
        </div>
        <ul class="footer-nav" style="margin-bottom: 35px">
          <li class="blue-circle">
            <%= link_to 'FAQS', faq_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'CONTACT US', contact_path, :class => 'white-font' %>
          </li>
        </ul>

        <div class="footer-grey-heading">
          <span class="grey-font">SOLUTIONS</span>
        </div>
        <ul class="footer-nav">
          <li class="blue-circle">
            <%= link_to 'TR5', tr5_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'TR20', tr20_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'TR50', tr50_path, :class => 'white-font' %>
          </li>
          <li class="blue-circle">
            <%= link_to 'MM90', mms90_path, :class => 'white-font' %>
          </li>
        </ul>
      </div>
      <div class="footer-inner-section">
        <div class="footer-grey-heading">
          <span class="grey-font">CONNECT</span>
        </div>
        <ul class="footer-nav" style="margin-bottom: 35px">
          <li style="display: flex">
            <i class="fa fa-map-marker" style="font-size: 25px; margin-right: 10px; color: #02B4FF"></i>
            <address class="white-font address">
              Sharjah Airport Free Zone
              SAIF Zone
              Q3 – 53
              P.O.Box: 514585
              Sharjah, United Arab Emirates
            </address>
          </li>
          <li style="display: flex; margin-bottom: 15px;">
            <i class="fa fa-phone" style="font-size: 25px; margin-right: 10px; color: #02B4FF"></i>
            <p class="white-font">+971 6-5272626</p>
          </li>
          <li style="display: flex; margin-bottom: 15px;">
            <i class="fa fa-fax" style="font-size: 20px; margin-right: 10px; color: #02B4FF"></i>
            <p class="white-font">+971 6-573 8597​​​​</p>
          </li>
          <li style="display: flex; margin-bottom: 15px;">
            <i class="fa fa-envelope" style="font-size: 18px; margin-right: 10px; color: #02B4FF"></i>
            <a class="white-font" style="color: white" href="mailto:support@drytrans.com">support@drytrans.com​​​​</a>
          </li>
        </ul>
      </div>

    </div>
  </div>

  <div class="blue-footer">
    <span class="white-font">AN AVACO SOLUTIONS FZC COMPANY</span>
  </div>
  <div class="black-footer">
    <ul class="white-font">
      <li>Drytrans, U.A.E</li>
      <li>|</li>
      <li>All Rights Reserved © 2018</li>
      <li>|</li>
      <li>Privacy Policy</li>
      <li><a href="https://time.is/Dubai"  target="_blank" style="color: white; text-decoration: underline">Time in Dubai:</a> <span id="todaysDate"></span></li>
    </ul>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, :class => 'navbar-brand' do %>
            <img class="image-box-image-new" src="https://storage.googleapis.com/wzukusers/user-22488641/images/5ab78ce0cb0065hDQIeh/DT-LOGO_d200.png" width="150" height="80" style="margin-top: 0px; margin-left: 0px;">
          <% end %>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'HOME', root_path, :tabindex => '-1', :class => current_class?(root_path) %></li>

            <li><%= link_to 'ABOUT', about_us_path, :class => current_class?(about_us_path) %></li>
            <li><%= link_to 'MOISTURE', moisture_path, :class => current_class?(moisture_path) %></li>
            <li>
<%
=begin %>
              <%= link_to solutions_path, :class => 'dropdown-toggle white-font disabled', data: { toggle: 'dropdown' } do %>
                SOLUTIONS
                <span class="caret"></span>
              <% end %>
<%
=end %>
              <%= link_to 'SOLUTIONS', solutions_path, :class => current_class?(solutions_path) %>

<%
=begin %>
              <ul class="dropdown-menu">
                <li><%= link_to 'TR5', tr5_path %></li>
                <li><%= link_to 'TR20', tr20_path %></li>
                <li><%= link_to 'TR50', tr50_path %></li>

                <li><%= link_to 'MMS90', mms90_path %></li>
              </ul>

<%
=end %>

            </li>
            <li><%= link_to 'EXPERIENCE', experience_path, :class => current_class?(experience_path) %></li>
            <li><%=  link_to 'CONTACT', contact_path, :class => current_class?(contact_path) %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>